version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    reviewers:
      - "bischoff99"
    open-pull-requests-limit: 5
    
  - package-ecosystem: "npm"
    directory: "/apps/easypost"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    reviewers:
      - "bischoff99"
      
  - package-ecosystem: "npm"
    directory: "/apps/veeqo"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    reviewers:
      - "bischoff99"
      
  - package-ecosystem: "docker"
    directory: "/apps/easypost"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
