version: '3.8'

services:
  dev:
    image: mcr.microsoft.com/devcontainers/typescript-node:20
    user: node
    working_dir: /workspace
    volumes:
      - ../:/workspace:cached
      - node-modules:/workspace/node_modules
      - pnpm-store:/home/node/.pnpm-store
    command: sleep infinity
    networks:
      - dev-network
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shipping_dev
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shipping_dev
    ports:
      - "5432:5432"
    networks:
      - dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - dev-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    command: redis-server --appendonly yes

volumes:
  node-modules:
  pnpm-store:
  postgres-data:
  redis-data:

networks:
  dev-network:
    driver: bridge